on:
  pull_request:
    branches:
      - '*'

name: Project check
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - uses: actions/checkout@master
        name: Checkout

      - name: Install dependencies
        run: npm ci

      - name: Lint project
        run: npm run lint

      - name: Build project
        run: npm run build